### ISSUE TITLE
Running it on linux doesent seem to do anything?

### ISSUE THREAD

**Issue by Tehcatninja** [Moonlington/FloSelfbot#29]
When i try to run it on linux after setting the binary executable and everything it doesent work.

**Comment by Moonlington** [comment]
Any error or something?

**Comment by DerfOh** [comment]
Hi! I am having problems running it on linux too. 

I have a valid token and it just denies the login, I followed the guide here: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

Here is as much info as I can give you. 
Do you have a way to generate application debug logs? I can put them here too, I appreciate the hard work.

Go info:
```
~/go/src/github.com/Moonlington/FloSelfbot $ go version
go version go1.8.3 linux/arm

~/go/src/github.com/Moonlington/FloSelfbot $ go env
GOARCH="arm"
GOBIN=""
GOEXE=""
GOHOSTARCH="arm"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/derfoh/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm"
GCCGO="gccgo"
GOARM=""
CC="gcc"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Console output:
```
~/go/src/github.com/Moonlington/FloSelfbot $ ./FloSelfbot
Something went wrong with logging in, check twice if your token is correct.
You can do so by editing/deleting config.toml
Press CTRL-C to exit.
^C
```

config.toml
```
~/go/src/github.com/Moonlington/FloSelfbot $ cat config.toml
Token = "MY_TOKENT_IS_A_SECRET"
Prefix = "&"
LogMode = true
LogModeMinBuffer = 0
LogModeMaxBuffer = 0
LogModeCompression = false
EmbedColor = ""
AFKPlay = false
MultiGameMinutes = 0
MultigameToggled = false
HighlightWebhook = ""
AutoDeleteSeconds = 0
SketchyMode = false
```

**Comment by Moonlington** [comment]
Sorry for the late reply but yeah, it's meant to be used on a user token, not bot one.

I know its against the TOS and the devs discourage it, but that only *really* applies to API abuse.

**Comment by LoganDark** [comment]
> I know its against the TOS

Selfbots are fine as long as they don't.. well, automate things.

No auto server joining, nothing like that. But commands that only YOU can trigger are fine, as long as they aren't API abuse.

**Comment by Tehcatninja** [comment]
@DerfOh If your looking for something to use with bot tokens i recommend Discord Console, it lets you enter commands directly into the terminal aswell.
(Sorry for necroposting but, i just read what you were talking about and decided to help :P)

**Comment by DerfOh** [comment]
@LoganDark Seems that you're right about automating. I would highly suggest checking this issue thread. https://github.com/discordapp/discord-api-docs/issues/69#issuecomment-223886862

**Comment by LoganDark** [comment]
That issue thread was the source of my information. I've already checked it.

**Comment by DerfOh** [comment]
Cool! @LoganDark this was a really good discussion I appreciate your input.

I apologize for hijacking this issue @Tehcatninja I think that @Moonlington can probably close this issue since we need the discordGO update mentioned in: #33 in order for functionality to move forward.
